// <auto-generated />
using System;
using ConsoleAppEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleAppEF.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20201220184618_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ConsoleAppEF.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("197d56c1-b203-4a75-8234-baff9bef3f1c"),
                            Age = 30,
                            Email = "Mubeen@gmail.com",
                            Name = "Mubeen",
                            Password = "123123"
                        },
                        new
                        {
                            Id = new Guid("71e1461a-c50d-4594-a86a-9305045e6ea2"),
                            Age = 15,
                            Email = "Tahir@gmail.com",
                            Name = "Tahir",
                            Password = "321321"
                        },
                        new
                        {
                            Id = new Guid("e735dbeb-c68b-4b42-aa11-79a017dfa93d"),
                            Age = 25,
                            Email = "Cheema@gmail.com",
                            Name = "Cheema",
                            Password = "123321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
